piro21_Ajax_Pirostagram/blog/urls.py
from django.urls import path
from .views import *

app_name = 'posts'
urlpatterns = [
    path('', post_list, name='post_list'),
    path('create/', post_create, name='post_create'),
    path('<int:pk>/', post_detail, name='post_detail'),
    path('<int:pk>/update', post_update, name='post_update'),
    path('<int:pk>/delete', post_delete, name='post_delete'),
    path('<int:pk>/comments/create', comment_create, name='comment_create'),
    path('<int:pk>/comments/delete', comment_delete, name='comment_delete'),
    path('like/', like, name='like'),
    path('comment/', comment, name='comment'),
    path('delete_comment/<int:pk>/', comment_delete, name='comment_delete'),

]

piro21_Ajax_Pirostagram/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

piro21_Ajax_Pirostagram/blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)  # 제목
    content = models.TextField()  # 내용
    created_at = models.DateTimeField(auto_now_add=True)  # 작성 시간

    def __str__(self):
        return self.title


class Like(models.Model):
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)  # Post 모델의 외래키

    def __str__(self):
        return f'Like for {self.post.title}'


class Comment(models.Model):
    content = models.TextField()  # 댓글의 내용
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)  # Post 모델의 외래키
    created_at = models.DateTimeField(auto_now_add=True)  # 댓글 작성 시간

    def __str__(self):
        return f'Comment by {self.post.title}'

piro21_Ajax_Pirostagram/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json

from .models import Post, Comment, Like


# Create your views here.


def post_list(request):
    posts = Post.objects.all()

    context = {'posts': posts}
    return render(request, 'list.html', context)


@csrf_exempt
def post_create(request):
    if request.method == 'POST':
        Post.objects.create(
            title=request.POST['title'],
            content=request.POST['content']
        )
        return redirect('/')

    return render(request, 'create.html')


def post_detail(request, pk):
    post = Post.objects.get(id=pk)

    comments = Comment.objects.filter(post=pk).order_by('-created_at')
    count = post.likes.count()
    c_count = post.comments.count()
    context = {
        'post': post,
        'comments': comments,
        'count': count,
        'c_count': c_count
    }
    return render(request, 'read.html', context)


@csrf_exempt
def post_update(request, pk):
    post = Post.objects.get(id=pk)
    context = {'post': post}
    if request.method == 'POST':
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.save()
        return redirect(f'/{post.pk}/')
    return render(request, 'update.html', context)


@csrf_exempt
def post_delete(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(id=pk)
        post.delete()
        return redirect('/')


@csrf_exempt
def comment_create(request, pk):
    if request.method == 'POST':
        posts = Post.objects.get(id=pk)
        Comment.objects.create(
            post=posts,
            content=request.POST['content']
        )
    return redirect(f'{pk}')


def comment_delete(request, pk):
    if request.method == 'POST':
        comments = Comment.objects.get(id=pk)
        comments.delete()
        return JsonResponse({'id': 'zz'})


@csrf_exempt
def like(request):
    req = json.loads(request.body)
    post_id = req['id']
    Like.objects.create(post_id=post_id)
    return JsonResponse({'id': post_id})


@csrf_exempt
def comment(request):
    print('gd')
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            post_id = data['id']
            content = data.get('content', '')
            print(post_id, content)
            comments = Comment.objects.create(post_id=post_id, content=content)

            return JsonResponse({'id': comments.id, 'content': content})
        except (KeyError, json.JSONDecodeError):
            return JsonResponse({'error': 'Invalid data'}, status=400)
    return JsonResponse({'error': 'Invalid request method'}, status=405)


@csrf_exempt
def like_ajax(request):
    if request.method == 'POST':
        req = json.loads(request.body)
        post_id = req['id']
        button_type = req['type']

        post = Post.objects.get(id=post_id)

        if button_type == 'like':
            post.like += 1
        else:
            post.dislike += 1
        post.save()

    return JsonResponse({'id': post_id, 'type': button_type})

piro21_Ajax_Pirostagram/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 작성</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .like-button {
            cursor: pointer;
            color: blue;
        }

        .like-button.liked {
            color: red;
        }
    </style>
</head>
<body>
<div class="container mt-5">
    <h2>글 작성</h2>
    <form id="createPostForm" action="{% url 'posts:post_create' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">제목</label>
            <input type="text" class="form-control" id="title" name="title" required>
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" id="content" rows="5" name="content" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">작성</button>
    </form>
</div>

</body>
</html>

piro21_Ajax_Pirostagram/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Posts</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <div class="row">
        <div class="col-12 d-flex justify-content-between align-items-center">
            <h1 class="mb-4">Blog Posts</h1>
            <a href="{% url 'posts:post_create' %}" class="btn btn-primary">글쓰기</a>
        </div>
        <div class="col-12">
            {% for post in posts %}
                <a href="{% url 'posts:post_detail' post.pk %}">
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text">{{ post.content|linebreaksbr }}</p>
                            <p class="card-text"><small class="text-muted">Posted on {{ post.created_at }}</small></p>
                        </div>
                    </div>
                </a>
            {% empty %}
                <p>No posts available.</p>
            {% endfor %}
        </div>
    </div>
</div>

</body>
</html>

piro21_Ajax_Pirostagram/templates/read.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 읽기</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .like-button {
            cursor: pointer;
            color: blue;
        }

        .like-button.liked {
            color: red;
        }
    </style>
</head>
<body>
<div class="container mt-5">
    <h2>글 읽기</h2>
    <div id="post" class="mb-4">
        <h3 id="postTitle">{{ post.title }}</h3>
        <p id="postContent">{{ post.content }}</p>
        <p class="like-button" id="likeButton" onclick="onClickLike({{ post.id }}, 'like')">좋아요
            <span id="likeCount">{{ count }}</span></p>
        <a href="{% url 'posts:post_update' post.id %}" class="btn btn-primary">글 수정</a>
        <form action="{% url 'posts:post_delete' post.id %}" method="POST" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">글 삭제</button>
        </form>
    </div>
    <hr>
    <h4>댓글 작성</h4>
    <div class="form-group">
        <textarea class="form-control" id="comment" rows="2" required></textarea>
    </div>
    <button class="btn btn-secondary" onclick="onClickComment({{ post.id }})">댓글 작성</button>

    <hr>
    <h4 class="comment-num">댓글 {{ c_count }}</h4>
    <div id="commentContainer">
        {% for comment in comments %}
            <div id="comment-{{ comment.id }}">
                <p>{{ comment.content }}</p>
                <form method="POST" action="{% url 'posts:comment_delete' comment.id %}">
                    {% csrf_token %}
                    <button type="submit" class="deleteButton" data-id="{{ comment.id }}">삭제</button>
                </form>
                <hr>
            </div>
        {% endfor %}
    </div>

</div>

</body>
<script>
    const requestComment = new XMLHttpRequest();
    const onClickComment = (id) => {
        const commentText = document.getElementById('comment').value;

        const url = "/comment/";
        requestComment.open("POST", url, true);
        requestComment.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );

        const params = JSON.stringify({id: id, content: commentText});
        requestComment.send(params.toString());
    }

    requestComment.onreadystatechange = () => {
        if (requestComment.readyState === XMLHttpRequest.DONE) {
            if (requestComment.status < 400) {
                const {id, content} = JSON.parse(requestComment.response)

                // 댓글 목록을 가져옴
                let commentList = document.getElementById('commentList');

                // 댓글이 없을 경우 commentList를 생성
                if (!commentList) {
                    commentList = document.createElement('div');
                    commentList.id = 'commentList';
                    commentList.className = 'container';
                    document.body.appendChild(commentList);
                }

                // 새로운 댓글을 추가
                const newComment = document.createElement('div');
                newComment.id = `comment-${id}`;

                const commentText = document.createElement('p');
                commentText.textContent = content;

                const deleteForm = document.createElement('form');
                deleteForm.method = 'post';
                deleteForm.action = `/delete_comment/${id}/`;

                const csrfToken = document.createElement('input');
                csrfToken.type = 'hidden';
                csrfToken.name = 'csrfmiddlewaretoken';
                csrfToken.value = getCsrfToken();

                const deleteButton = document.createElement('button');
                deleteButton.type = 'submit';
                deleteButton.textContent = '삭제';
                deleteButton.className = 'deleteButton'
                deleteButton.setAttribute('data-id', id);

                deleteForm.appendChild(csrfToken);
                deleteForm.appendChild(deleteButton);

                const hr = document.createElement('hr');

                newComment.appendChild(commentText);
                newComment.appendChild(deleteForm);
                newComment.appendChild(hr);

                commentList.insertBefore(newComment, commentList.firstChild);

                const element = document.querySelector('.comment-num');
                const originHTML = element.innerHTML;
                const [text, num] = originHTML.split(" ");
                const count = Number(num) + 1;

                element.innerHTML = `${text} ${count}`;
            }
        }
    }

    document.addEventListener('DOMContentLoaded', () => {
        // 모든 삭제 버튼에 이벤트 리스너 추가
        document.querySelectorAll('.deleteButton').forEach(button => {
            button.addEventListener('click', (event) => {
                event.preventDefault(); // 폼 제출 방지

                const commentId = event.target.getAttribute('data-id');
                deleteComment(commentId);
            });
        });
    });

    const deleteComment = (id) => {
        const requestDelete = new XMLHttpRequest();
        const url = `/delete_comment/${id}/`;

        requestDelete.open("POST", url, true);
        requestDelete.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );

        // CSRF 토큰 설정
        const csrfToken = getCsrfToken();
        requestDelete.setRequestHeader("X-CSRFToken", csrfToken);

        requestDelete.send();

        requestDelete.onreadystatechange = () => {
            if (requestDelete.readyState === XMLHttpRequest.DONE) {
                if (requestDelete.status < 400) {
                    const commentElement = document.getElementById(`comment-${id}`);
                    if (commentElement) {
                        commentElement.remove();
                    }


                    const element = document.querySelector('.comment-num');
                    const originHTML = element.innerHTML;
                    const [text, num] = originHTML.split(" ");
                    const count = Number(num) - 1;
                    element.innerHTML = `${text} ${count}`;
                }
            }
        };
    };


    function getCsrfToken() {
        return document.querySelector('[name=csrfmiddlewaretoken]').value;
    }
</script>


<script>
    const requestLike = new XMLHttpRequest();

    const onClickLike = (id) => {
        const url = "/like/";
        requestLike.open("POST", url, true);
        requestLike.setRequestHeader(
            "Co0ntent-Type",
            "application/x-www-form-urlencoded"
        );
        requestLike.send(JSON.stringify({id: id}));
    }

    requestLike.onreadystatechange = () => {
        if (requestLike.readyState === XMLHttpRequest.DONE) {
            if (requestLike.status < 400) {
                const {id} = JSON.parse(requestLike.response)
                const element = document.querySelector(`#likeCount`);
                const originHTML = element.innerHTML;
                const count = Number(originHTML) + 1;

                element.innerHTML = `${count}`;
            }
        }
    }

</script>
</html>

piro21_Ajax_Pirostagram/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 업데이트</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <h2>글 업데이트</h2>
    <form id="updatePostForm" method="POST" action="{% url 'posts:post_update' post.pk %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">제목</label>
            <input type="text" class="form-control" id="title" name="title"
                   value="{{ post.title }}"
                   required>
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" id="content" rows="5" name="content"
                      value="{{ post.content }}"
                      required>{{ post.content }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">업데이트</button>
    </form>
</div>

</body>
</html>