SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('idea.urls')),
    path('develop/', include('develop.urls')),
    path('member/', include('member.urls')),
    path('star/', include('star.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/idea/urls.py
from django.urls import path
from .views import *

app_name = 'idea'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('update/<int:pk>/', update, name='update'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('change-interest/', change_interest, name='change_interest'),

]

SWIDEA_SITE/star/urls.py
from django.urls import path
from .views import *

app_name = 'star'

urlpatterns = [
    path('int<pk>/', push, name='push'),
    path('int<pk>/delete', delete, name='delete'),
]

SWIDEA_SITE/idea/models.py
from django.db import models

from develop.models import Develop
from member.models import Member
from django.utils import timezone


# Create your models here.

class Idea(models.Model):
    user = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name='작성자', null=True)
    devtool = models.ForeignKey(Develop, on_delete=models.CASCADE, verbose_name='개발툴', null=True)
    title = models.CharField(max_length=30)
    content = models.TextField()
    interest = models.IntegerField(default=0)
    img_url = models.ImageField(upload_to='images/%Y%m%d', default='images/basic.jpg')
    created_date = models.DateTimeField('작성일', default=timezone.now)

SWIDEA_SITE/idea/forms.py
from django import forms

from develop.models import Develop
from member.models import Member
from .models import Idea


class IdeaForm(forms.ModelForm):
    # member = forms.ModelChoiceField(queryset=Member.objects.all(), label='멤버')  # 없어도 될듯
    # develop = forms.ModelChoiceField(queryset=Develop.objects.all(), label='개발')

    class Meta:
        model = Idea
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

SWIDEA_SITE/idea/views.py
from django.shortcuts import render, redirect

from idea.models import Idea
from star.models import Star
from .forms import IdeaForm
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse


# Create your views here.
@csrf_exempt
def change_interest(request):
    if request.method == 'POST':
        idea_id = request.POST.get('idea_id')
        action = request.POST.get('action')

        try:
            idea = Idea.objects.get(id=idea_id)
            if action == 'increase':
                idea.interest += 1
            elif action == 'decrease':
                idea.interest -= 1
            idea.save()

            return JsonResponse({'new_interest': idea.interest})
        except Idea.DoesNotExist:
            return JsonResponse({'error': 'Idea not found'}, status=404)

    return JsonResponse({'error': 'Invalid request'}, status=400)


def main(request):
    sort = request.GET.get('sort', 'newest')
    query = request.GET.get('q', '')

    sort_order = {
        'star': 'star__created_date',
        'title': 'title',
        'newest': '-created_date',
        'oldest': 'created_date'
    }

    ideas = Idea.objects.all()
    if query:
        ideas = ideas.filter(title__icontains=query)

    if sort == 'star':
        # 외래키로 연결된 Star가 존재하는 Idea만 필터링
        ideas = ideas.filter(star__isnull=False).distinct()

    ideas = ideas.order_by(sort_order.get(sort, '-created_date'))

    paginator = Paginator(ideas, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    star = Star.objects.all()
    context = {'ideas': page_obj,
               'stars': star}
    return render(request, 'idea/list.html', context)

def create(request):
    if request.method == 'POST':
        form = IdeaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('idea:main')
    form = IdeaForm()
    context = {'form': form}
    return render(request, 'idea/create.html', context)


def detail(request, pk):
    idea = Idea.objects.get(pk=pk)
    star_exist = Star.objects.filter(idea=pk).exists()
    print(star_exist)
    context = {'idea': idea,
               'pk': pk,
               'star_exist': star_exist}
    return render(request, 'idea/detail.html', context)


def delete(request, pk):
    Idea.objects.get(pk=pk).delete()
    return redirect('idea:main')


def update(request, pk):
    idea = Idea.objects.get(pk=pk)

    if request.method == 'POST':
        form = IdeaForm(request.POST, request.FILES, instance=idea)
        if form.is_valid():
            form.save()
            return redirect('idea:detail', pk=pk)  # 저장 후 detail 뷰로 리디렉션
    else:
        form = IdeaForm(instance=idea)  # 기존 인스턴스로 폼 초기화

    context = {'pk': pk, 'form': form}
    return render(request, 'idea/update.html', context)

SWIDEA_SITE/templates/idea/create.html
{% extends 'base.html' %}


{%block content%}
<div class="container mt-5">
  <h2>아이디어 생성</h2>
  <form 
    action="{% url 'idea:create' %}"
    method="post"
    enctype="multipart/form-data"
    class="needs-validation" novalidate
  >
    {% csrf_token %}
    <div class="form-row">
      {% for field in form %}
        <div class="form-group col-md-6">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-success">등록하기</button>
  </form>
</div>

{%endblock%}

SWIDEA_SITE/templates/idea/detail.html
{% extends 'base.html' %}


{% block content %}
    <div class="container mt-5">
        <div class="card text-center">
            <div class="card-header">
                <h3 class="text-black">아이디어 세부사항</h3>
                <p class="text-black" style="font-weight: bold">제목: {{ idea.title }}</p>
            </div>
            <div class="card-body">
                <img src="{{ idea.img_url.url }}" alt="X" class="img-fluid"
                     style="max-height: 150px;">
                {% if star_exist %}
                    <h4 class="mt-3">{{ idea.pk }} 번째 게시물 <span class="text-warning">★</span></h4>
                {% else %}
                    <h4 class="mt-3">{{ idea.pk }} 번째 게시물 <span class="text-warning">☆</span></h4>

                {% endif %}
                <p>1) 아이디어 관심도: {{ idea.interest }}</p>
                <p>2) 개발 툴: {{ idea.devtool.name }}</p>
                <p>3) 아이디어 설명: {{ idea.content }} </p>
                <form action="{% url 'idea:delete' idea.pk %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger mr-2" type="submit">삭제</button>
                    <a href="{% url 'idea:main' %}" class="btn btn-secondary mr-2">목록</a>
                    <a href="{% url 'idea:update' idea.pk %}" class="btn btn-primary mr-2">수정</a>
                </form>

                {% if star_exist %}
                    <form action="{% url 'star:delete' idea.pk %}" method="POST" class="mt-5">
                        {% csrf_token %}
                        <button class="btn btn-danger">찜 취소하기</button>
                    </form>
                {% else %}
                    <form action="{% url 'star:push' idea.pk %}" method="POST" class="mt-5">
                        {% csrf_token %}
                        <button class="btn btn-success">찜하기</button>
                    </form>
                {% endif %}


            </div>
        </div>
    </div>

{% endblock %}

SWIDEA_SITE/templates/idea/list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mt-4">아이디어 관리</h1>
        <div class="row mb-4">
            <div class="col-md-8">
                <select class="form-control" id="sortOrder">
                    <option value="newest">최신순</option>
                    <option value="star">찜하기순</option>
                    <option value="title">이름순</option>

                    <option value="oldest">과거순</option>
                </select>
            </div>
            <div class="col-md-4">
                <form method="GET" action="">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="제목으로 검색"
                               value="{{ request.GET.q }}">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit">검색</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            {% for idea in ideas %}
                <div class="col-md-3">
                    <div class="card">
                        <img src="{{ idea.img_url.url }}" class="card-img-top" alt="이미지">
                   

                        <div class="card-body">
                            <a href="{% url 'idea:detail' idea.pk %}">
                                <h5 class="card-title">{{ idea.title }}</h5>
                            </a>
                            <p class="card-text">작성자: {{ idea.user.name }}</p>
                            <p class="card-text">개발툴: {{ idea.devtool.name }}</p>
                            <p class="card-text">관심도:
                                <button class="change-interest" data-id="{{ idea.id }}" data-action="decrease">-
                                </button>
                                <span id="interest-{{ idea.id }}">{{ idea.interest }}</span>
                                <button class="change-interest" data-id="{{ idea.id }}" data-action="increase">+
                                </button>
                            </p>

                            <p class="card-text">작성일: {{ idea.created_date }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <nav aria-label="페이지 내비게이션" class="d-flex justify-content-center">
            <ul class="pagination">
                {% if ideas.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ ideas.previous_page_number }}" aria-label="이전">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% for num in ideas.paginator.page_range %}
                    <li class="page-item {% if ideas.number == num %}active{% endif %}">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endfor %}
                {% if ideas.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ ideas.next_page_number }}" aria-label="다음">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const query = new URLSearchParams(window.location.search);
            const sortOrder = query.get('sort');
            if (sortOrder) {
                document.getElementById('sortOrder').value = sortOrder;
            }
        });

        document.getElementById('sortOrder').addEventListener('change', function () {
            const selectedValue = this.value;
            const query = new URLSearchParams(window.location.search);
            query.set('sort', selectedValue);
            window.location.search = query.toString();
        });
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).on('click', '.change-interest', function () {
            var ideaId = $(this).data('id');
            var action = $(this).data('action');

            $.ajax({
                url: '/change-interest/',
                type: 'POST',
                data: {
                    'idea_id': ideaId,
                    'action': action,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (data) {
                    $('#interest-' + ideaId).text(data.new_interest);
                },
                error: function (xhr, status, error) {
                    console.error("Error updating interest:", error);
                }
            });
        });
    </script>

{% endblock %}

SWIDEA_SITE/templates/idea/update.html
{% extends 'base.html' %}


{%block content%}
<div class="container mt-5">
  <h2>아이디어 생성</h2>
  <form 
    action="{% url 'idea:update' pk %}"
    method="post"
    enctype="multipart/form-data"
    class="needs-validation" novalidate
  >
    {% csrf_token %}
    <div class="form-row">
      {% for field in form %}
        <div class="form-group col-md-6">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-success">수정 완료</button>
  </form>
</div>

{%endblock%}