SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('idea.urls')),
    path('develop/', include('develop.urls')),
    path('member/', include('member.urls')),
    path('star/', include('star.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/develop/urls.py
from django.urls import path
from .views import *

app_name = 'develop'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('update/<int:pk>/', update, name='update'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'),

]

SWIDEA_SITE/idea/urls.py
from django.urls import path
from .views import *

app_name = 'idea'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('update/<int:pk>/', update, name='update'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('change-interest/', change_interest, name='change_interest'),

]

SWIDEA_SITE/develop/models.py
from django.db import models


# Create your models here.

class Develop(models.Model):
    name = models.CharField(max_length=30)
    kind = models.CharField(max_length=30)
    content = models.TextField()

    def __str__(self):
        return self.name

SWIDEA_SITE/develop/forms.py
from django import forms
from .models import Develop


class DevelopForm(forms.ModelForm):
    class Meta():
        model = Develop
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

SWIDEA_SITE/develop/views.py
from django.shortcuts import render, redirect

from idea.models import Idea
from .models import Develop
from .forms import DevelopForm


# Create your views here.

def main(request):
    develop = Develop.objects.all()
    context = {'develop': develop}

    return render(request, 'develop/list.html', context)


def create(request):
    form = DevelopForm(request.POST, request.FILES)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect('develop:main')
    form = DevelopForm()
    context = {'form': form}
    return render(request, 'develop/create.html', context)


def detail(request, pk):
    develop = Develop.objects.get(pk=pk)
    id_develop = Idea.objects.filter(devtool_id=pk)
    context = {'develop': develop,
               'id_tool': id_develop}
    return render(request, 'develop/detail.html', context)


def delete(request, pk):
    Develop.objects.get(pk=pk).delete()
    return redirect('develop:main')


def update(request, pk):
    develop = Develop.objects.get(pk=pk)
    form = DevelopForm(instance=develop)
    if request.method == 'POST':
        form = DevelopForm(request.POST, request.FILES, instance=develop)
        if form.is_valid():
            form.save()
            return redirect('develop:detail', pk=pk)

    context = {'pk': pk, 'form': form}
    return render(request, 'develop/update.html', context)

SWIDEA_SITE/templates/develop/create.html
{% extends 'base.html' %}


{%block content%}
<div class="container mt-5">
  <h2>Create a New Develop</h2>
  <form 
    action="{% url 'develop:create' %}"
    method="post"
    enctype="multipart/form-data"
    class="needs-validation" novalidate
  >
    {% csrf_token %}
    <div class="form-row">
      {% for field in form %}
        <div class="form-group col-md-6">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-success">등록하기</button>
  </form>
</div>

{%endblock%}

SWIDEA_SITE/templates/develop/detail.html
{% extends 'base.html' %}


{% block content %}
    <div class="container mt-5">
        <div class="card text-center">
            <div class="card-header">
                <h3 class="text-black">개발툴 세부사항</h3>
                <p class="text-black" style="font-weight: bold">제목: {{ develop.title }}</p>
            </div>
            <div class="card-body">


                <p>1) 개발툴 종류: {{ develop.tool }}</p>
                <p>2) 해당 개발툴 설명: {{ develop.kind }}</p>
                <p>3) 만들 수 있는 SW 목록 </p>
                {% for tool in id_tool %}
                    <div class="mb-3">
                    <a href="{% url 'idea:detail' tool.pk %}" 
                    >{{ tool.title }}</a>
                    </div>
                {% endfor %}
            <div class="mt-5"></div>
                <form action="{% url 'develop:delete' develop.pk %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger mr-2" type="submit">삭제</button>
                    <a href="{% url 'develop:main' %}" class="btn btn-secondary mr-2">목록</a>
                    <a href="{% url 'develop:update' develop.pk %}" class="btn btn-primary mr-2">수정</a>
                 
                </form>


            </div>
        </div>
    </div>

{% endblock %}

SWIDEA_SITE/templates/develop/list.html
{% extends 'base.html' %}


{% block content %}
    <div class="container devtool-list">
        <h2>개발 툴 리스트</h2>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Kind</th>
                <th>Content</th>
            </tr>
            </thead>
            <tbody>
            {% for devtool in develop %}
                <tr>
                    <td>
                        <a href="{% url 'develop:detail' devtool.pk %}">
                            {{ devtool.name }}</a></td>

                    <td>{{ devtool.kind }}</td>
                    <td>{{ devtool.content }}</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

SWIDEA_SITE/templates/develop/update.html
{% extends 'base.html' %}


{%block content%}
<div class="container mt-5">
  <h2>Create a New Develop</h2>
  <form 
    action="{% url 'develop:update' pk %}"
    method="post"
    enctype="multipart/form-data"
    class="needs-validation" novalidate
  >
    {% csrf_token %}
    <div class="form-row">
      {% for field in form %}
        <div class="form-group col-md-6">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-success">수정 완료</button>
  </form>
</div>

{%endblock%}