SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('idea.urls')),
    path('develop/', include('develop.urls')),
    path('member/', include('member.urls')),
    path('star/', include('star.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/develop/urls.py
from django.urls import path
from .views import *

app_name = 'develop'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('update/<int:pk>/', update, name='update'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'),

]

SWIDEA_SITE/idea/urls.py
from django.urls import path
from .views import *

app_name = 'idea'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('update/<int:pk>/', update, name='update'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('change-interest/', change_interest, name='change_interest'),

]

SWIDEA_SITE/member/urls.py
# urls.py
from django.urls import path
from .views import *

app_name = 'member'

urlpatterns = [

    path('create', create, name='create'),
]

SWIDEA_SITE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My SW Idea Manage</title>
    <link rel="stylesheet" href="{% static 'path/to/fontawesome/css/all.min.css' %}">

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<header class="bg-dark text-white fixed-top mb-5" style="margin-bottom: 55px">
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="{% url 'idea:main' %}">My SW Idea Manage</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'member:create' %}">유저 등록</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'idea:create' %}">아이디어 등록</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'idea:main' %}">아이디어 관리</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'develop:create' %}">개발툴 등록</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'develop:main'  %}">개발툴 관리</a></li>
            </ul>
        </div>
    </nav>
</header>
<main style="margin-top: 80px">
    {% block content %}


    {% endblock %}
</main>

</body>
</html>